language: python
python:
  - "3.7"
matrix:
  include:

  - name: default Python + latest Sphinx

  # a few older Sphinx releases using default Python version
  - env: SPHINX="==1.8.0" BIBTEX="==0.4.2"
  - env: SPHINX="==1.8.5" BIBTEX="==0.4.2"
  - env: SPHINX="==2.0.0"
  - env: SPHINX="==2.1.0"
  - env: SPHINX="==2.1.2"

  # a few Python versions using latest Sphinx release
  - python: "3.4"
    env: BIBTEX="==0.4.2"
  - python: "3.5"
  - python: "3.6"
  - python: "nightly"
  #- python: "pypy3"

  - name: check for broken links
    script:
      - python3 -m sphinx doc/ doc/_build/ -b linkcheck

  # default Python + latest Sphinx on macOS
  - os: osx
    language: generic

addons:
  apt:
    packages:
      - pandoc
      - librsvg2-bin
  homebrew:
    update: true
    packages:
      - pandoc
      - librsvg
      - python3
install:
  - python3 -m pip install Sphinx$SPHINX
  - python3 -m pip install .
  - python3 -m pip install $(grep -iv bibtex doc/requirements.txt)
  - python3 -m pip install sphinxcontrib-bibtex$BIBTEX
script:
  - python3 -m nbsphinx
  - python3 -m sphinx doc/ doc/_build/ -b html
  - python3 -m sphinx doc/ doc/_build/ -b latex
  - python3 -m sphinx doc/ doc/_build/ -b epub
