# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build_docs:
    docker:
      - image: texlive/texlive

    working_directory: ~/checkout

    environment:
      PIP_INSTALL: python -m pip install --progress-bar off --upgrade

    steps:
      - checkout

      - store_artifacts:
          name: Uploading overview page
          path: .circleci/artifacts.html
          destination: artifacts.html

      - run:
          name: Installing apt Packages
          command: |
            apt-get -y update
            apt-get install -y --no-install-recommends python3-venv librsvg2-bin binutils pandoc
            # temporary, until docutils > 0.19.0 is released (see doc/requirements.txt):
            apt-get install -y --no-install-recommends subversion

      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "doc/requirements.txt" }}
            # fallbacks
            - v1-deps-{{ .Branch }}-
            - v1-deps-

      - run:
          name: Set up venv
          command: |
            python3 -m venv .venv
            echo "source .venv/bin/activate" >> $BASH_ENV

      - run:
          name: Installing nbsphinx
          command: |
            $PIP_INSTALL .

      - run:
          name: Installing doc Dependencies
          command: |
            $PIP_INSTALL -r doc/requirements.txt

      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-deps-{{ .Branch }}-{{ checksum "doc/requirements.txt" }}

      - run:
          name: Show pandoc version
          command: |
            pandoc --version

      - run:
          name: Building HTML
          command: |
            python3 setup.py build_sphinx -W -b html

      - store_artifacts:
          name: Uploading HTML files
          path: build/sphinx/html
          destination: html

      - run:
          name: Building LaTeX
          command: |
            python3 setup.py build_sphinx -W -b latex

      - run:
          name: Building PDF
          command: |
            cd build/sphinx/latex
            latexmk -pdflua

      - store_artifacts:
          name: Uploading PDF file
          path: build/sphinx/latex/nbsphinx.pdf
          destination: nbsphinx.pdf

workflows:
  version: 2
  build-me-my-docs:
    jobs:
      - build_docs
