name: Build HTML on macOS
on: [push, pull_request]
env:
  PYTHONWARNINGS: error
  PIP: python -m pip
  SPHINX: python -m sphinx -W --keep-going --color
jobs:
  html-macos:
    runs-on: macos-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install pandoc
      run: |
        brew install pandoc
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3
    - name: Double-check Python version
      run: |
        python --version
    - name: Install Python package
      env:
        # There is still a warning with pip version 24, even though this
        # is supposed to be fixed: https://github.com/pypa/pip/issues/11975
        PYTHONWARNINGS: error,default::DeprecationWarning
      run: |
        $PIP install .
    - name: Install docs dependencies
      env:
        # There is still a warning with pip version 24, even though this
        # is supposed to be fixed: https://github.com/pypa/pip/issues/11975
        PYTHONWARNINGS: error,default::DeprecationWarning
      run: |
        $PIP install -r doc/requirements.txt
    - name: Build HTML
      env:
        # There is a weird warning from jupyter_core (https://github.com/jupyter/jupyter_core/issues/398)
        PYTHONWARNINGS: error,default::DeprecationWarning
      run: |
        $SPHINX doc/ _build/html/
